### PR TITLE
improve docs

### PR DESCRIPTION
**Pull request by dnsbty**
Updates docs a little bit

### CODE REVIEW

**Review by tylerwray — APPROVED** [review]
Looks great

**Comment by sgtpepper43** [comment]
I see what you're doing @dnsbty

**Comment by dnsbty** [comment]
@sgtpepper43 this was just an example for the open source training I did yesterday. I don't even know who I need to talk to about getting maintainer access...

**Comment by sgtpepper43** [comment]
Oh, haha, I thought you were trying to get an easy PR for hacktoberfest 😂

**Pull request merged**
